# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

## !USE TEXT THEME
theme: jekyll-text-theme # Gem-based Jekyll Themes
# remote_theme: kitian616/jekyll-TeXt-theme # Jekyll Remote Theme, see https://github.com/benbalter/jekyll-remote-theme for more information.
#
# ,--------.      ,--.   ,--. ,--.
# '--.  .--',---.  \  `.'  /,-'  '-.
#    |  |  | .-. :  .'    \ '-.  .-'
#    |  |  \   --. /  .'.  \  |  |
#    `--'   `----''--'   '--' `--'
## => Site Settings
##############################
text_skin: default # "default" (default), "dark", "forest", "ocean", "chocolate", "orange"
highlight_theme: default # "default" (default), "tomorrow", "tomorrow-night", "tomorrow-night-eighties", "tomorrow-night-blue", "tomorrow-night-bright"
url     : popchor-mannheim.de # the base hostname & protocol for your site e.g. https://www.someone.com
baseurl : # does not include hostname
title   : POPCHOR MANNHEIM
description: > # this means to ignore newlines until "Language & timezone"
  Popchor Mannheim


## => Language and Timezone
##############################
lang: de # the language of your site, default as "en"
timezone: Europe/Berlin # see https://en.wikipedia.org/wiki/List_of_tz_database_time_zones for the available values


## => Author and Social
##############################
author:
  type      : organization
  name      : Popchor Mannheim
  url       :
  avatar    : # path or url of avatar image (square)
  bio       : I am an amazing person.
  email     :
  facebook  : # "user_name" the last part of your profile url, e.g. https://www.facebook.com/user_name
  github    : # "user_name" the last part of your profile url, e.g. https://github.com/user_name


## => GitHub Repository (if the site is hosted by GitHub)
##############################
repository: popchor-mannheim/popchor-mannheim.github.io
repository_tree: main


## => Paths
##############################
paths:
  root    : # title link url, "/" (default)
  home    : # home layout url, "/" (default)

## => Post
##############################
## excerpt
excerpt_separator: <!--more-->

## TOC
toc:
  selectors: # "h1,h2,h3" (default)


## => Markdown Enhancements
##############################
## Mathjax
mathjax: # false (default), true
mathjax_autoNumber: # false (default), true

## Mermaid
mermaid: # false (default), true

## Chart
chart: # false (default), true


## => Paginate
##############################
paginate: 8
paginate_path: /page:num # don't change this unless for special need


## => Sources
##############################
sources: cdnjs # bootcdn (default), unpkg


## => Sharing
##############################
sharing:
  provider: false # false (default), "addtoany", "addthis", "custom"

  ## AddThis
  addthis:
    id: # AddThis pubid, e.g. ra-5xxxxxxxxxxx


## => Comments
##############################
comments:
  provider: false # false (default), "disqus", "gitalk", "valine", "custom"

  ## Disqus
  disqus:
    shortname: # the Disqus shortname for the site

  ## Gitalk
  # please refer to https://github.com/gitalk/gitalk for more info.
  gitalk:
    clientID    : # GitHub Application Client ID
    clientSecret: # GitHub Application Client Secret
    repository  : # GitHub repo
    owner       : # GitHub repo owner
    admin: # GitHub repo owner and collaborators, only these guys can initialize GitHub issues, IT IS A LIST.
      # - your GitHub Id

  ## Valine
  # please refer to https://valine.js.org/en/ for more info.
  valine:
    app_id      : # LeanCloud App id
    app_key     : # LeanCloud App key
    placeholder : # Prompt information
    visitor     : # false (default)
    meta        : # "[nick, mail, link]" (default) nickname, E-mail, Personal-site


## => Pageview
##############################
pageview:
  provider: false

## => Search
##############################
search:
  provider: false

## => Analytics
##############################
analytics:
  provider: false


## => Build
##############################
markdown    : kramdown
highlighter : rouge
permalink   : date

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - law-stuff.md
  - law-stuff.html
  - pages/**
  # - assets/android-chrome-192x192.png
  # - assets/android-chrome-512x512.png
  # - assets/browserconfig.xml
  # - assets/favicon-16x16.png
  # - assets/favicon-32x32.png
  # - assets/mstile-144x144.png
  # - assets/mstile-150x150.png
  # - assets/mstile-310x150.png
  # - assets/mstile-310x310.png
  # - assets/mstile-70x70.png
  # - assets/safari-pinned-tab.svg

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: article
      sharing: false
      license: false
      aside:
        toc: true
      show_edit_on_github: false
      show_subscribe: false
      pageview: false


## => Plugins
##############################
plugins:
#  - jekyll-feed
#  - jekyll-paginate
#  - jekyll-sitemap
#  - jemoji